### ISSUE TITLE
SwiftUI Preview Bug Unable to run project after importing.

### ISSUE THREAD

**Issue by pratikbaid3** [ApplebaumIan/SwiftUI-Apple-Watch-Decimal-Pad#1]
Hi. This is the error that I get after importing the package in my watch os project
```Cannot find 'WKInterfaceDevice' in scope```

**Comment by ApplebaumIan** [comment]
Hey there! I'm currently on vacation but I should be able to look into this within the week. I will say installing Swift Packages to Apple Watch can be tricky. Did you follow the installation instructions? Also if you are able you can send me a copy of your project with the error. Last question would be what version of Xcode are you running and what is the WatchOS deployment target?

**Comment by ApplebaumIan** [comment]
@pratikbaid3 So I have looked into this and I think Apple must have changed something in the WKInterface API that is breaking SwiftUI Preview support. This is obviously super lame since its one of SwiftUI's best features. It seems that my keyboard clicks are what's breaking support of it... I will look into whether I can patch this or if I just have to remove the click sounds ☹️  


In the meantime, the keyboard actually works fine in the simulator/device if you do a `⌘R`.

**Comment by pratikbaid3** [comment]
Thanks for looking into this @ApplebaumIan. The click sound isn't a very important feature (but a good to have) for my use case so maybe I can create a fork and just remove that for now while it gets fixed. Thanks again for taking the time out to look into this.

**Comment by ApplebaumIan** [comment]
@pratikbaid3 Try my `fixSwiftUIPreview` branch. I tested this and it seems to bring back SwiftUI preview while retaining the keyboard clicks!
